/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OOrgIdTTeamIdRouteImport } from './routes/o.$orgId.t.$teamId'
import { Route as OOrgIdTTeamIdIndexRouteImport } from './routes/o.$orgId.t.$teamId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdTTeamIdRoute = OOrgIdTTeamIdRouteImport.update({
  id: '/o/$orgId/t/$teamId',
  path: '/o/$orgId/t/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdTTeamIdIndexRoute = OOrgIdTTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdTTeamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdRouteWithChildren
  '/o/$orgId/t/$teamId/': typeof OOrgIdTTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdRouteWithChildren
  '/o/$orgId/t/$teamId/': typeof OOrgIdTTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/o/$orgId/t/$teamId' | '/o/$orgId/t/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/o/$orgId/t/$teamId'
  id: '__root__' | '/' | '/o/$orgId/t/$teamId' | '/o/$orgId/t/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OOrgIdTTeamIdRoute: typeof OOrgIdTTeamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/t/$teamId': {
      id: '/o/$orgId/t/$teamId'
      path: '/o/$orgId/t/$teamId'
      fullPath: '/o/$orgId/t/$teamId'
      preLoaderRoute: typeof OOrgIdTTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/t/$teamId/': {
      id: '/o/$orgId/t/$teamId/'
      path: '/'
      fullPath: '/o/$orgId/t/$teamId/'
      preLoaderRoute: typeof OOrgIdTTeamIdIndexRouteImport
      parentRoute: typeof OOrgIdTTeamIdRoute
    }
  }
}

interface OOrgIdTTeamIdRouteChildren {
  OOrgIdTTeamIdIndexRoute: typeof OOrgIdTTeamIdIndexRoute
}

const OOrgIdTTeamIdRouteChildren: OOrgIdTTeamIdRouteChildren = {
  OOrgIdTTeamIdIndexRoute: OOrgIdTTeamIdIndexRoute,
}

const OOrgIdTTeamIdRouteWithChildren = OOrgIdTTeamIdRoute._addFileChildren(
  OOrgIdTTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OOrgIdTTeamIdRoute: OOrgIdTTeamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
