/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known/oauth-authorization-server/api/auth'
import { Route as OOrgIdTTeamIdRouteRouteImport } from './routes/o/$orgId/t/$teamId/route'
import { Route as OOrgIdTTeamIdIndexRouteImport } from './routes/o/$orgId/t/$teamId/index'
import { Route as OOrgIdTTeamIdManageRouteRouteImport } from './routes/o/$orgId/t/$teamId/manage/route'
import { Route as OOrgIdTTeamIdAccountRouteRouteImport } from './routes/o/$orgId/t/$teamId/account/route'
import { Route as OOrgIdTTeamIdManageIndexRouteImport } from './routes/o/$orgId/t/$teamId/manage/index'
import { Route as OOrgIdTTeamIdAccountIndexRouteImport } from './routes/o/$orgId/t/$teamId/account/index'
import { Route as OOrgIdTTeamIdManageTeamsRouteImport } from './routes/o/$orgId/t/$teamId/manage/teams'
import { Route as OOrgIdTTeamIdManageRolesRouteImport } from './routes/o/$orgId/t/$teamId/manage/roles'
import { Route as OOrgIdTTeamIdManageMembersRouteImport } from './routes/o/$orgId/t/$teamId/manage/members'
import { Route as OOrgIdTTeamIdAccountSessionsRouteImport } from './routes/o/$orgId/t/$teamId/account/sessions'
import { Route as OOrgIdTTeamIdAccountSecurityRouteImport } from './routes/o/$orgId/t/$teamId/account/security'
import { Route as OOrgIdTTeamIdAccountProfileRouteImport } from './routes/o/$orgId/t/$teamId/account/profile'
import { Route as OOrgIdTTeamIdAccountConnectedAppsRouteImport } from './routes/o/$orgId/t/$teamId/account/connected-apps'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)
const OOrgIdTTeamIdRouteRoute = OOrgIdTTeamIdRouteRouteImport.update({
  id: '/o/$orgId/t/$teamId',
  path: '/o/$orgId/t/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgIdTTeamIdIndexRoute = OOrgIdTTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgIdTTeamIdRouteRoute,
} as any)
const OOrgIdTTeamIdManageRouteRoute =
  OOrgIdTTeamIdManageRouteRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => OOrgIdTTeamIdRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountRouteRoute =
  OOrgIdTTeamIdAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => OOrgIdTTeamIdRouteRoute,
  } as any)
const OOrgIdTTeamIdManageIndexRoute =
  OOrgIdTTeamIdManageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgIdTTeamIdManageRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountIndexRoute =
  OOrgIdTTeamIdAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgIdTTeamIdAccountRouteRoute,
  } as any)
const OOrgIdTTeamIdManageTeamsRoute =
  OOrgIdTTeamIdManageTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => OOrgIdTTeamIdManageRouteRoute,
  } as any)
const OOrgIdTTeamIdManageRolesRoute =
  OOrgIdTTeamIdManageRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => OOrgIdTTeamIdManageRouteRoute,
  } as any)
const OOrgIdTTeamIdManageMembersRoute =
  OOrgIdTTeamIdManageMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OOrgIdTTeamIdManageRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountSessionsRoute =
  OOrgIdTTeamIdAccountSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => OOrgIdTTeamIdAccountRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountSecurityRoute =
  OOrgIdTTeamIdAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => OOrgIdTTeamIdAccountRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountProfileRoute =
  OOrgIdTTeamIdAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => OOrgIdTTeamIdAccountRouteRoute,
  } as any)
const OOrgIdTTeamIdAccountConnectedAppsRoute =
  OOrgIdTTeamIdAccountConnectedAppsRouteImport.update({
    id: '/connected-apps',
    path: '/connected-apps',
    getParentRoute: () => OOrgIdTTeamIdAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/two-factor': typeof TwoFactorRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdRouteRouteWithChildren
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/o/$orgId/t/$teamId/account': typeof OOrgIdTTeamIdAccountRouteRouteWithChildren
  '/o/$orgId/t/$teamId/manage': typeof OOrgIdTTeamIdManageRouteRouteWithChildren
  '/o/$orgId/t/$teamId/': typeof OOrgIdTTeamIdIndexRoute
  '/o/$orgId/t/$teamId/account/connected-apps': typeof OOrgIdTTeamIdAccountConnectedAppsRoute
  '/o/$orgId/t/$teamId/account/profile': typeof OOrgIdTTeamIdAccountProfileRoute
  '/o/$orgId/t/$teamId/account/security': typeof OOrgIdTTeamIdAccountSecurityRoute
  '/o/$orgId/t/$teamId/account/sessions': typeof OOrgIdTTeamIdAccountSessionsRoute
  '/o/$orgId/t/$teamId/manage/members': typeof OOrgIdTTeamIdManageMembersRoute
  '/o/$orgId/t/$teamId/manage/roles': typeof OOrgIdTTeamIdManageRolesRoute
  '/o/$orgId/t/$teamId/manage/teams': typeof OOrgIdTTeamIdManageTeamsRoute
  '/o/$orgId/t/$teamId/account/': typeof OOrgIdTTeamIdAccountIndexRoute
  '/o/$orgId/t/$teamId/manage/': typeof OOrgIdTTeamIdManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/two-factor': typeof TwoFactorRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdIndexRoute
  '/o/$orgId/t/$teamId/account/connected-apps': typeof OOrgIdTTeamIdAccountConnectedAppsRoute
  '/o/$orgId/t/$teamId/account/profile': typeof OOrgIdTTeamIdAccountProfileRoute
  '/o/$orgId/t/$teamId/account/security': typeof OOrgIdTTeamIdAccountSecurityRoute
  '/o/$orgId/t/$teamId/account/sessions': typeof OOrgIdTTeamIdAccountSessionsRoute
  '/o/$orgId/t/$teamId/manage/members': typeof OOrgIdTTeamIdManageMembersRoute
  '/o/$orgId/t/$teamId/manage/roles': typeof OOrgIdTTeamIdManageRolesRoute
  '/o/$orgId/t/$teamId/manage/teams': typeof OOrgIdTTeamIdManageTeamsRoute
  '/o/$orgId/t/$teamId/account': typeof OOrgIdTTeamIdAccountIndexRoute
  '/o/$orgId/t/$teamId/manage': typeof OOrgIdTTeamIdManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/two-factor': typeof TwoFactorRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/o/$orgId/t/$teamId': typeof OOrgIdTTeamIdRouteRouteWithChildren
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/o/$orgId/t/$teamId/account': typeof OOrgIdTTeamIdAccountRouteRouteWithChildren
  '/o/$orgId/t/$teamId/manage': typeof OOrgIdTTeamIdManageRouteRouteWithChildren
  '/o/$orgId/t/$teamId/': typeof OOrgIdTTeamIdIndexRoute
  '/o/$orgId/t/$teamId/account/connected-apps': typeof OOrgIdTTeamIdAccountConnectedAppsRoute
  '/o/$orgId/t/$teamId/account/profile': typeof OOrgIdTTeamIdAccountProfileRoute
  '/o/$orgId/t/$teamId/account/security': typeof OOrgIdTTeamIdAccountSecurityRoute
  '/o/$orgId/t/$teamId/account/sessions': typeof OOrgIdTTeamIdAccountSessionsRoute
  '/o/$orgId/t/$teamId/manage/members': typeof OOrgIdTTeamIdManageMembersRoute
  '/o/$orgId/t/$teamId/manage/roles': typeof OOrgIdTTeamIdManageRolesRoute
  '/o/$orgId/t/$teamId/manage/teams': typeof OOrgIdTTeamIdManageTeamsRoute
  '/o/$orgId/t/$teamId/account/': typeof OOrgIdTTeamIdAccountIndexRoute
  '/o/$orgId/t/$teamId/manage/': typeof OOrgIdTTeamIdManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/dashboard'
    | '/device'
    | '/two-factor'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/o/$orgId/t/$teamId'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/o/$orgId/t/$teamId/account'
    | '/o/$orgId/t/$teamId/manage'
    | '/o/$orgId/t/$teamId/'
    | '/o/$orgId/t/$teamId/account/connected-apps'
    | '/o/$orgId/t/$teamId/account/profile'
    | '/o/$orgId/t/$teamId/account/security'
    | '/o/$orgId/t/$teamId/account/sessions'
    | '/o/$orgId/t/$teamId/manage/members'
    | '/o/$orgId/t/$teamId/manage/roles'
    | '/o/$orgId/t/$teamId/manage/teams'
    | '/o/$orgId/t/$teamId/account/'
    | '/o/$orgId/t/$teamId/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/dashboard'
    | '/device'
    | '/two-factor'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/o/$orgId/t/$teamId'
    | '/o/$orgId/t/$teamId/account/connected-apps'
    | '/o/$orgId/t/$teamId/account/profile'
    | '/o/$orgId/t/$teamId/account/security'
    | '/o/$orgId/t/$teamId/account/sessions'
    | '/o/$orgId/t/$teamId/manage/members'
    | '/o/$orgId/t/$teamId/manage/roles'
    | '/o/$orgId/t/$teamId/manage/teams'
    | '/o/$orgId/t/$teamId/account'
    | '/o/$orgId/t/$teamId/manage'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/dashboard'
    | '/device'
    | '/two-factor'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/o/$orgId/t/$teamId'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/o/$orgId/t/$teamId/account'
    | '/o/$orgId/t/$teamId/manage'
    | '/o/$orgId/t/$teamId/'
    | '/o/$orgId/t/$teamId/account/connected-apps'
    | '/o/$orgId/t/$teamId/account/profile'
    | '/o/$orgId/t/$teamId/account/security'
    | '/o/$orgId/t/$teamId/account/sessions'
    | '/o/$orgId/t/$teamId/manage/members'
    | '/o/$orgId/t/$teamId/manage/roles'
    | '/o/$orgId/t/$teamId/manage/teams'
    | '/o/$orgId/t/$teamId/account/'
    | '/o/$orgId/t/$teamId/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  DeviceRoute: typeof DeviceRoute
  TwoFactorRoute: typeof TwoFactorRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OOrgIdTTeamIdRouteRoute: typeof OOrgIdTTeamIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
    '/o/$orgId/t/$teamId': {
      id: '/o/$orgId/t/$teamId'
      path: '/o/$orgId/t/$teamId'
      fullPath: '/o/$orgId/t/$teamId'
      preLoaderRoute: typeof OOrgIdTTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgId/t/$teamId/': {
      id: '/o/$orgId/t/$teamId/'
      path: '/'
      fullPath: '/o/$orgId/t/$teamId/'
      preLoaderRoute: typeof OOrgIdTTeamIdIndexRouteImport
      parentRoute: typeof OOrgIdTTeamIdRouteRoute
    }
    '/o/$orgId/t/$teamId/manage': {
      id: '/o/$orgId/t/$teamId/manage'
      path: '/manage'
      fullPath: '/o/$orgId/t/$teamId/manage'
      preLoaderRoute: typeof OOrgIdTTeamIdManageRouteRouteImport
      parentRoute: typeof OOrgIdTTeamIdRouteRoute
    }
    '/o/$orgId/t/$teamId/account': {
      id: '/o/$orgId/t/$teamId/account'
      path: '/account'
      fullPath: '/o/$orgId/t/$teamId/account'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountRouteRouteImport
      parentRoute: typeof OOrgIdTTeamIdRouteRoute
    }
    '/o/$orgId/t/$teamId/manage/': {
      id: '/o/$orgId/t/$teamId/manage/'
      path: '/'
      fullPath: '/o/$orgId/t/$teamId/manage/'
      preLoaderRoute: typeof OOrgIdTTeamIdManageIndexRouteImport
      parentRoute: typeof OOrgIdTTeamIdManageRouteRoute
    }
    '/o/$orgId/t/$teamId/account/': {
      id: '/o/$orgId/t/$teamId/account/'
      path: '/'
      fullPath: '/o/$orgId/t/$teamId/account/'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountIndexRouteImport
      parentRoute: typeof OOrgIdTTeamIdAccountRouteRoute
    }
    '/o/$orgId/t/$teamId/manage/teams': {
      id: '/o/$orgId/t/$teamId/manage/teams'
      path: '/teams'
      fullPath: '/o/$orgId/t/$teamId/manage/teams'
      preLoaderRoute: typeof OOrgIdTTeamIdManageTeamsRouteImport
      parentRoute: typeof OOrgIdTTeamIdManageRouteRoute
    }
    '/o/$orgId/t/$teamId/manage/roles': {
      id: '/o/$orgId/t/$teamId/manage/roles'
      path: '/roles'
      fullPath: '/o/$orgId/t/$teamId/manage/roles'
      preLoaderRoute: typeof OOrgIdTTeamIdManageRolesRouteImport
      parentRoute: typeof OOrgIdTTeamIdManageRouteRoute
    }
    '/o/$orgId/t/$teamId/manage/members': {
      id: '/o/$orgId/t/$teamId/manage/members'
      path: '/members'
      fullPath: '/o/$orgId/t/$teamId/manage/members'
      preLoaderRoute: typeof OOrgIdTTeamIdManageMembersRouteImport
      parentRoute: typeof OOrgIdTTeamIdManageRouteRoute
    }
    '/o/$orgId/t/$teamId/account/sessions': {
      id: '/o/$orgId/t/$teamId/account/sessions'
      path: '/sessions'
      fullPath: '/o/$orgId/t/$teamId/account/sessions'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountSessionsRouteImport
      parentRoute: typeof OOrgIdTTeamIdAccountRouteRoute
    }
    '/o/$orgId/t/$teamId/account/security': {
      id: '/o/$orgId/t/$teamId/account/security'
      path: '/security'
      fullPath: '/o/$orgId/t/$teamId/account/security'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountSecurityRouteImport
      parentRoute: typeof OOrgIdTTeamIdAccountRouteRoute
    }
    '/o/$orgId/t/$teamId/account/profile': {
      id: '/o/$orgId/t/$teamId/account/profile'
      path: '/profile'
      fullPath: '/o/$orgId/t/$teamId/account/profile'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountProfileRouteImport
      parentRoute: typeof OOrgIdTTeamIdAccountRouteRoute
    }
    '/o/$orgId/t/$teamId/account/connected-apps': {
      id: '/o/$orgId/t/$teamId/account/connected-apps'
      path: '/connected-apps'
      fullPath: '/o/$orgId/t/$teamId/account/connected-apps'
      preLoaderRoute: typeof OOrgIdTTeamIdAccountConnectedAppsRouteImport
      parentRoute: typeof OOrgIdTTeamIdAccountRouteRoute
    }
  }
}

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerApiAuthRoute:
      DotwellKnownOauthAuthorizationServerApiAuthRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

interface OOrgIdTTeamIdAccountRouteRouteChildren {
  OOrgIdTTeamIdAccountConnectedAppsRoute: typeof OOrgIdTTeamIdAccountConnectedAppsRoute
  OOrgIdTTeamIdAccountProfileRoute: typeof OOrgIdTTeamIdAccountProfileRoute
  OOrgIdTTeamIdAccountSecurityRoute: typeof OOrgIdTTeamIdAccountSecurityRoute
  OOrgIdTTeamIdAccountSessionsRoute: typeof OOrgIdTTeamIdAccountSessionsRoute
  OOrgIdTTeamIdAccountIndexRoute: typeof OOrgIdTTeamIdAccountIndexRoute
}

const OOrgIdTTeamIdAccountRouteRouteChildren: OOrgIdTTeamIdAccountRouteRouteChildren =
  {
    OOrgIdTTeamIdAccountConnectedAppsRoute:
      OOrgIdTTeamIdAccountConnectedAppsRoute,
    OOrgIdTTeamIdAccountProfileRoute: OOrgIdTTeamIdAccountProfileRoute,
    OOrgIdTTeamIdAccountSecurityRoute: OOrgIdTTeamIdAccountSecurityRoute,
    OOrgIdTTeamIdAccountSessionsRoute: OOrgIdTTeamIdAccountSessionsRoute,
    OOrgIdTTeamIdAccountIndexRoute: OOrgIdTTeamIdAccountIndexRoute,
  }

const OOrgIdTTeamIdAccountRouteRouteWithChildren =
  OOrgIdTTeamIdAccountRouteRoute._addFileChildren(
    OOrgIdTTeamIdAccountRouteRouteChildren,
  )

interface OOrgIdTTeamIdManageRouteRouteChildren {
  OOrgIdTTeamIdManageMembersRoute: typeof OOrgIdTTeamIdManageMembersRoute
  OOrgIdTTeamIdManageRolesRoute: typeof OOrgIdTTeamIdManageRolesRoute
  OOrgIdTTeamIdManageTeamsRoute: typeof OOrgIdTTeamIdManageTeamsRoute
  OOrgIdTTeamIdManageIndexRoute: typeof OOrgIdTTeamIdManageIndexRoute
}

const OOrgIdTTeamIdManageRouteRouteChildren: OOrgIdTTeamIdManageRouteRouteChildren =
  {
    OOrgIdTTeamIdManageMembersRoute: OOrgIdTTeamIdManageMembersRoute,
    OOrgIdTTeamIdManageRolesRoute: OOrgIdTTeamIdManageRolesRoute,
    OOrgIdTTeamIdManageTeamsRoute: OOrgIdTTeamIdManageTeamsRoute,
    OOrgIdTTeamIdManageIndexRoute: OOrgIdTTeamIdManageIndexRoute,
  }

const OOrgIdTTeamIdManageRouteRouteWithChildren =
  OOrgIdTTeamIdManageRouteRoute._addFileChildren(
    OOrgIdTTeamIdManageRouteRouteChildren,
  )

interface OOrgIdTTeamIdRouteRouteChildren {
  OOrgIdTTeamIdAccountRouteRoute: typeof OOrgIdTTeamIdAccountRouteRouteWithChildren
  OOrgIdTTeamIdManageRouteRoute: typeof OOrgIdTTeamIdManageRouteRouteWithChildren
  OOrgIdTTeamIdIndexRoute: typeof OOrgIdTTeamIdIndexRoute
}

const OOrgIdTTeamIdRouteRouteChildren: OOrgIdTTeamIdRouteRouteChildren = {
  OOrgIdTTeamIdAccountRouteRoute: OOrgIdTTeamIdAccountRouteRouteWithChildren,
  OOrgIdTTeamIdManageRouteRoute: OOrgIdTTeamIdManageRouteRouteWithChildren,
  OOrgIdTTeamIdIndexRoute: OOrgIdTTeamIdIndexRoute,
}

const OOrgIdTTeamIdRouteRouteWithChildren =
  OOrgIdTTeamIdRouteRoute._addFileChildren(OOrgIdTTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  DeviceRoute: DeviceRoute,
  TwoFactorRoute: TwoFactorRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OOrgIdTTeamIdRouteRoute: OOrgIdTTeamIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
